version: 2.1
orbs:
  ruby-rails-setup: later/ruby-rails-setup@0.0.3

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:3.1.2
      environment:
                RAILS_ENV: test
caches:
  - &bundle_cache -repo
commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache
      - run: bundle install --path vendor/bundle
      - run: cp .sample.env .env
      - run: bundle exec rake db:setup
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle
  run_specs:
    steps:
      - run:
          name: run specs
          command: rspec spec
jobs:
  specs:
    executor: default
    steps:
      - defaults
      - run_specs

workflows:
  version: 2
  build:
    jobs:
      - specs:
